# Generated by Django 5.2.1 on 2025-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0004_rename_text_resume_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='pict',
            field=models.ImageField(blank=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='resume_creator.skills_description'),
        ),
    ]
