# Generated by Django 5.2.1 on 2025-06-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0005_skills_description_alter_resume_pict_resume_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills_description',
            new_name='Attachment',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='attachments',
            field=models.ManyToManyField(related_name='attachments', to='resume_creator.attachment'),
        ),
    ]
