# Generated by Django 5.2.1 on 2025-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0007_remove_attachment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='education',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='work_experience',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='work_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
