# Generated by Django 5.2.1 on 2025-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0008_attachment_email_alter_attachment_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FilePathField(default=None, verbose_name='resume_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('no_category', ' '), ('education', 'Освіта'), ('individual_info', 'Інформація про себе'), ('work_experience', 'Досвід роботи')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ResumeFile',
        ),
    ]
