# Generated by Django 5.2.1 on 2025-07-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0013_alter_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='file_path',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
    ]
