# Generated by Django 5.2.1 on 2025-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0014_remove_resume_file_resume_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('base', 'Звичайний'), ('clasic', 'Класичний')], default='base', max_length=30),
            preserve_default=False,
        ),
    ]
