# Generated by Django 5.2.1 on 2025-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0015_resume_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(blank=True, choices=[('base', 'Звичайний'), ('classic', 'Класичний')], max_length=30),
        ),
    ]
