# Generated by Django 5.2.1 on 2025-08-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_creator', '0016_alter_resume_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='project_idea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='project_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='attachment',
            name='used_technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('no_category', ' '), ('education', 'Освіта'), ('individual_info', 'Інформація про себе'), ('work_experience', 'Досвід роботи'), ('project', 'Проект')], max_length=30),
        ),
    ]
